// Collision categories (bit flags)
pub const CATEGORY_TERRAIN: u64 = 1 << 0;
pub const CATEGORY_PLAYER: u64 = 1 << 1;
pub const CATEGORY_PROJECTILE: u64 = 1 << 2;
pub const CATEGORY_SENSOR: u64 = 1 << 3;
pub const CATEGORY_DYNAMIC: u64 = 1 << 4;
pub const CATEGORY_UNBREAKABLE: u64 = 1 << 5;
pub const CATEGORY_BLOOD: u64 = 1 << 6;
pub const CATEGORY_GIBLET: u64 = 1 << 7;
pub const CATEGORY_HOOK: u64 = 1 << 8;

// Collision masks - what each category collides with
pub const MASK_TERRAIN = CATEGORY_TERRAIN | CATEGORY_PLAYER | CATEGORY_PROJECTILE | CATEGORY_BLOOD | CATEGORY_DYNAMIC | CATEGORY_GIBLET | CATEGORY_SENSOR | CATEGORY_UNBREAKABLE | CATEGORY_HOOK;
pub const MASK_UNBREAKABLE = MASK_TERRAIN;

pub const MASK_PLAYER = CATEGORY_TERRAIN | CATEGORY_DYNAMIC | CATEGORY_GIBLET | CATEGORY_PROJECTILE | CATEGORY_BLOOD | CATEGORY_SENSOR | CATEGORY_UNBREAKABLE;
pub const MASK_PLAYER_LOWER_BODY = CATEGORY_TERRAIN | CATEGORY_DYNAMIC | CATEGORY_GIBLET | CATEGORY_PROJECTILE | CATEGORY_SENSOR | CATEGORY_UNBREAKABLE;

pub const MASK_PROJECTILE = CATEGORY_TERRAIN | CATEGORY_PLAYER | CATEGORY_DYNAMIC | CATEGORY_GIBLET | CATEGORY_UNBREAKABLE | CATEGORY_HOOK;

pub const MASK_DYNAMIC = CATEGORY_TERRAIN | CATEGORY_PLAYER | CATEGORY_PROJECTILE | CATEGORY_BLOOD | CATEGORY_DYNAMIC | CATEGORY_GIBLET | CATEGORY_SENSOR | CATEGORY_UNBREAKABLE | CATEGORY_HOOK;

pub const MASK_BLOOD = CATEGORY_TERRAIN | CATEGORY_DYNAMIC | CATEGORY_UNBREAKABLE;

pub const MASK_GIBLET = CATEGORY_TERRAIN | CATEGORY_PLAYER | CATEGORY_PROJECTILE | CATEGORY_DYNAMIC | CATEGORY_GIBLET | CATEGORY_SENSOR | CATEGORY_UNBREAKABLE | CATEGORY_HOOK;

pub const MASK_SENSOR_FOOT = CATEGORY_TERRAIN | CATEGORY_DYNAMIC | CATEGORY_GIBLET | CATEGORY_UNBREAKABLE;
pub const MASK_SENSOR_WALL = CATEGORY_TERRAIN | CATEGORY_DYNAMIC | CATEGORY_UNBREAKABLE;
pub const MASK_SENSOR_GOAL = CATEGORY_PLAYER;
pub const MASK_SENSOR_SPAWN = CATEGORY_PLAYER;

// Hook interacts with everything it can attach to
pub const MASK_HOOK = CATEGORY_TERRAIN | CATEGORY_UNBREAKABLE | CATEGORY_DYNAMIC | CATEGORY_PROJECTILE | CATEGORY_GIBLET;

// Explosion shrapnel
pub const MASK_EXPLOSION_SHRAPNEL = CATEGORY_TERRAIN | CATEGORY_DYNAMIC | CATEGORY_GIBLET | CATEGORY_PLAYER | CATEGORY_UNBREAKABLE;

// Query filters for overlap tests
pub const MASK_EXPLOSION_QUERY = CATEGORY_TERRAIN | CATEGORY_DYNAMIC | CATEGORY_GIBLET;
pub const MASK_BLOOD_QUERY = CATEGORY_TERRAIN | CATEGORY_DYNAMIC | CATEGORY_UNBREAKABLE;

// Per-player group index: shapes with the same negative group index never collide.
// Offset avoids conflicts with existing group indices (-1 shrapnel, -3 blood).
const playerGroupOffset: i32 = 10;

pub fn playerGroupIndex(playerId: usize) i32 {
    return -(@as(i32, @intCast(playerId)) + playerGroupOffset);
}
